# This workflow is a reusable one called by other workflows
name: (template) CLI template

on:
  workflow_call:
    # Variables to set when calling this reusable workflow
    inputs:
      boot_type:
        required: true
        type: string
      bootstrap_provider:
        required: true
        type: string
      cluster_name:
        required: true
        type: string
      cluster_number:
        required: true
        type: string
      cluster_namespace:
        required: true
        type: string
      control_plane_provider:
        required: true
        type: string
      destroy_runner:
        required: true
        type: boolean
      k8s_downstream_version:
        required: true
        type: string
      k8s_upstream_version:
        required: true
        type: string
      node_number:
        required: true
        type: string
      operator_repo:
        required: true
        type: string
      public_domain:
        required: true
        type: string
      public_fqdn:
        required: true
        type: string
      qase_project_code:
        required: true
        type: string
      qase_run_id:
        required: true
        type: string
      runner_label:
        required: true
        type: string
      test_type:
        required: true
        type: string

    # Job outputs to export for caller workflow
    outputs:
      steps_status:
        description: Status of the executed test jobs
        value: ${{ join(jobs.*.outputs.steps_status, ' ') }}

    # Secrets to set when calling this reusable workflow
    secrets:
      credentials:
      qase_api_token:

jobs:
  cli:
    if: ${{ inputs.test_type == 'capi_cli' }}
    uses: ./.github/workflows/sub_capi_cli.yaml
    secrets:
      credentials: ${{ secrets.credentials }}
      qase_api_token: ${{ secrets.qase_api_token }}
    with:
      boot_type: ${{ inputs.boot_type }}
      bootstrap_provider: ${{ inputs.bootstrap_provider }}
      cluster_name: ${{ inputs.cluster_name }}
      cluster_namespace: ${{ inputs.cluster_namespace }}
      control_plane_provider: ${{ inputs.control_plane_provider }}
      destroy_runner: ${{ inputs.destroy_runner }}
      k8s_downstream_version: ${{ inputs.k8s_downstream_version }}
      node_number: ${{ inputs.node_number }}
      operator_repo: ${{ inputs.operator_repo }}
      public_domain: ${{ inputs.public_domain }}
      public_fqdn: ${{ inputs.public_fqdn }}
      qase_project_code: ${{ inputs.qase_project_code }}
      qase_run_id: ${{ inputs.qase_run_id }}
      runner_label: ${{ inputs.runner_label }}
      test_type: ${{ inputs.test_type }}
      k8s_upstream_version: ${{ inputs.k8s_upstream_version }}
